use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# Web.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :web, Web.Endpoint,
  http: [port: System.get_env("PORT")],
  url: [scheme: "https", host: "extracurricular.elixirschool.com", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  secret_key_base: System.get_env("PHOENIX_SECRET_KEY"),
  root: ".",
  version: Application.spec(:web, :vsn)

config :appsignal, :config,
  active: true,
  name: "extracurricular",
  push_api_key: System.get_env("APPSIGNAL_API_KEY"),
  env: :production
